import type { Metadata } from "next";
import "../src/styles/globals.scss";
import Navbar from "@/src/Shared/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar />
          {children}

        </main>
      </body>
    </html>
  );
}
